path:
    totes: raw_data/active_totes_20201123.csv
    availability: raw_data/Availability_with_Grey&Blue_1811-2511.csv
    faults: raw_data/scs_tote_matched.csv
    save: raw_data/results

settings:
    aggregation: Module
    fault_level: code
    target: "Blue Tote Loss"
    