path:
    source: 'Local'
    totes: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/active_totes_20201210.csv'
    availability: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/Availability_with_Grey&Blue_1811-0912.csv'
    faults: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/Faults20_11-10_12.csv'
    save: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Results/ML_Output.csv'

parameters:
    speed: 470
    picker_present: 0.91
    availability: 0.71

