path: #Area to specify data source, and input, output and package paths
    source: 'SQL/Local/Test'
    totes: 'Optional argument to specify data path if running local or test'
    availability: 'Optional argument to specify data path if running local or test'
    faults: 'Optional argument to specify data path if running local or test'
    save: 'Path of output file save location'
    package: 'Path of where package exists on server'

