source: 'Local'
mode: 'Manual'
path:
    totes: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/Dan_Data/active_totes.csv'
    availability: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/Dan_Data/availability.csv'
    faults: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/Dan_Data/SCADA_faults.csv'
    save: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Results/'
    package: 'C:/Users/jamie.williams/desktop/scs/'
