path:
    source: 'Local'
    totes: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/at_prod.csv'
    availability: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/av_prod.csv'
    faults: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Data/fa_dec_jan.csv'
    save: 'C:/Users/Jamie.williams/OneDrive - Newton Europe Ltd/Castle Donnington/Results/'
    package: 'C:/Users/jamie.williams/desktop/scs/'

parameters:
    speed: 470
    picker_present: 0.91
    availability: 0.71

report:
    start: '2021-24-01 06:00:00'
    end: '2021-24-01 18:00:00'

