source: 'Test'
mode: 'Manual'
path:
    totes: './scsavailability/tests/TestData/at_test.csv'
    availability: './scsavailability/tests/TestData/av_test.csv'
    faults: './scsavailability/tests/TestData/fa_test.csv'
    save: './scsavailability/tests/TestData/Test Results/'
    package: './'


